
set nocompatible 
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

""" Plugins """
Plugin 'VundleVim/Vundle.vim'
"Plugin 'tpope/vim-fugitive'
"Plugin 'git://git.wincent.com/command-t.git'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/syntastic'
Plugin 'mboughaba/i3config.vim'
Plugin 'dylanaraps/wal.vim'
Plugin 'mhinz/vim-startify'

call vundle#end()          
filetype plugin indent on 

""" General settings """
set shortmess=I
"set spell
syntax enable
set tabstop=4
set t_Co=256
set relativenumber
set number
set background=dark
map <C-n> :NERDTreeToggle<CR>

let NERDTreeShowLineNumbers=1
"autocmd vimenter * NERDTree

""" Syntastic settings """
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

 """ Theme  """
colorscheme wal
"let g:airline_theme = ''
let airline_powerline_fonts = 1
