
set nocompatible 
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" ===== Plugins ================

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
"Plugin 'git://git.wincent.com/command-t.git'
"Plugin 'file:///home/gmarik/path/to/plugin'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/syntastic'
Plugin 'flazz/vim-colorschemes'
Plugin 'edkolev/tmuxline.vim'
Plugin 'easymotion/vim-easymotion'
Plugin 'mboughaba/i3config.vim'
Plugin 'dylanaraps/wal.vim'

call vundle#end()          
filetype plugin indent on 
"filetype plugin on


" ===== General settings =======

set shortmess=I
"set spell
:filetype plugin on
:syntax on
set t_Co=256
set number
set relativenumber
set background=dark
map <C-n> :NERDTreeToggle<CR>
au BufWinLeave * mkview
au BufWinEnter * silent loadview


" ===== Syntastic settings =====

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

 
" ===== Airline ================
colorscheme wal
"let g:airline_theme = 'murmur'
let airline_powerline_fonts = 1
