#! /usr/bin/env sh

wp='lotr-baraddur.png'
kc='orange'

sed -i 's/#define\ xsc1\ blue/!#define\ xcs1\ blue/' ~/.Xresources
sed -i 's/!#define\ xsc1\ #CB3B16/#define\ xcs1\ #CB3B16/' ~/.Xresources
xrdb -merge ~/.Xresources
wal -i ~/.local/share/wallpapers/$wp \
	-a "90" \
	-o ~/.bin/qutebrowser_reload.py 1> /dev/null
wal_steam -w 1> /dev/null
alienfx -t $kc
feh --bg-scale --no-xinerama ~/.local/share/wallpapers/$wp
