#! /usr/bin/env sh

wp='spring.png'
kc='blue'

wal -i $HOME/.local/share/wallpapers/$wp \
	-a "90" \
	-o $HOME/.bin/qutebrowser_reload.py 1> /dev/null
wal_steam -w 1> /dev/null
alienfx -t $kc
feh --bg-scale --no-xinerama ~/.local/share/wallpapers/$wp
